<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!--<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">-->
<html>
	<head>
		<title><?php echo _("Distrito la Colorada");?></title>
	  	<?php 
			$this->headLink()->appendStylesheet("/layoutguest/orange/css/style.css");
			$this->headLink()->appendStylesheet("/layoutguest/orange/siteapp.css");
		?>
		<?php //echo $this->jQuery(); ?>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>

  		<div id="container_header"><p>&nbsp;</p></div>
  			<div id="main">
  				<div id="header">
	  <div id="banner">
	    <h1><span>Your</span> Business</h1>
	  </div><!--close banner-->
	  <div id="banner_slogan">
	    <h2>Company Slogan Here</h2>
	  </div><!--close banner_slogan-->	  
      <div id="menubar">
        <div id="nav">
			<?php echo $this->navigation()->menu(); ?>
     	</div>
      </div><!--close menubar-->
    </div><!--close header-->
				<div id="site_content">	
	  				<div class="sidebar_container">
						<div class="sidebar">
          					<h2>Latest Blog</h2>
			  				<div class="sidebar_item">
								<h4>March 2012</h4>
	            				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
			  					<div class="button_small">
			      					<a href="#">Read more</a>
			    				</div><!--close button_small-->
	          				</div><!--close sidebar_item--> 
        				</div><!--close sidebar-->    
        				 		
						<div class="sidebar">
				        	<h2>Latest Blog</h2>
						  	<div class="sidebar_item">
								<h4>March 2012</h4>
				            	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
						  		<div class="button_small">
						      		<a href="#">Read more</a>
						    	</div><!--close button_small-->
				          	</div><!--close sidebar_item--> 
				        </div><!--close sidebar-->  
				        
						<div class="sidebar">
          					<h2>Latest Blog</h2>
		  					<div class="sidebar_item">
								<h4>March 2012</h4>
	            				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
			  					<div class="button_small">
			      					<a href="#">Read more</a>
			    				</div><!--close button_small-->
          					</div><!--close sidebar_item--> 
        				</div><!--close sidebar-->  
       				</div><!--close sidebar_container-->
	 
	  				<div id="content">
        				<?php echo $this->layout()->content; ?>
      				</div><!--close content-->
    
				</div><!--close site_content-->
    
			<div id="footer">
      			<a href="http://validator.w3.org/check?uri=referer">Valid XHTML</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">Valid CSS</a> | <a href="http://www.pdphoto.org/">Images</a> | website template by <a href="http://www.araynordesign.co.uk">ARaynorDesign</a>
    		</div><!--close footer-->    
		</div><!--close main-->  
  
		<div id="container_footer">&nbsp;</div>
  			<p style="float: left;padding: 0;">&nbsp;</p>
  		<?php echo $this->headScript(); //very important?>
		<div style="margin: 1em 0 3em 0; text-align: center;"></div>
	</body>
</html>
