<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/UnityClub.js","text/javascript");?>
<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _("Filter Unity Club"));?>
	<div id="containerFormFilter">
		<?php echo $this->formFilter; ?>
	</div>
	<br>
	<?php echo $this->tableHeader('unityClubHeader', _("Unities Club"));?>
	<?php echo $this->tableList("tblUnityClub");?>
	<div class="buttons right">
		<?php echo $this->buttonRemove("delete-unityClub", $this->translate('Remove'), $this->url(array('action'=>'delete')));?>
		<?php echo $this->buttonAdd("create-unityClub", $this->translate('Add'), $this->url(array('action'=>'create')));?>
	</div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	var unityClub = new com.em.UnityClub();

	// network
	unityClub.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'update')); ?>',
		toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Name'); ?>',
		'<?php echo $this->translate('Motto'); ?>',
		'<?php echo $this->translate('Description'); ?>',
		'<?php echo $this->translate('Club Pathfinder'); ?>',
		'<?php echo $this->translate('Changed'); ?>',
		'<?php echo $this->translate('Changed'); ?>');
	unityClub.setHeaders(headers);
	// configuration of widgets
	unityClub.configureTable('#tblUnityClub', true);

	// CRUD
	unityClub.clickToAdd('#create-unityClub');
	unityClub.clickToUpdate('#tblUnityClub a[id^=update-unityClub-]');
	unityClub.clickToDelete('#delete-unityClub');
	unityClub.configureAuto('input#nameFilter');
});
</script>