<div id="dialog-form" title="<?php echo $this->translate('Add User Group'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>	
</div>

<script type="text/javascript">
//	$("#privilege").multiselect();
	$("#privilege").multiselect(/*{
		noneSelectedText: 'Select Something (required)',
        selectedList: 3,
        classes: 'my-select'
		}*/).multiselectfilter();

//	$("#name").bind('keyup', function(e) {
//		var nameVal = $('#name').val();
//		if (nameVal != '') {
//			$("#name").parent().find('.error').remove();
//		}
//	});
	
	com.em.UserGroup.prototype.dialogButtons = {
			'<?php echo $this->translate('Save'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'UserGroup', 'action'=>'create-save'));?>',
				type: "POST", 
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						return false;
					}
					
					com.em.UserGroup.prototype.processingDisplay(true);
					return true;
				},
				
				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.UserGroup.prototype.showAlert(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.message == 'name_warning') {
							
							} else {		
								$("#name").parent().find('.error').remove();	

								$("#name").parent().append('<ul id="error-name" class="error"><li>'+data.message+'</li> </ul>');						
								com.em.UserGroup.prototype.showAlert(data.message, {header: com.em.Alert.ERROR});
							}
						}
					}
				},
				
				complete: function(jqXHR, textStatus) {
					com.em.UserGroup.prototype.processingDisplay(false);
					
				},
				
				error: function(jqXHR, textStatus, errorThrown) {
					dialogFormEducationLevel.dialog('close');
					com.em.UserGroup.prototype.showAlert(errorThrown,{header : com.em.Alert.ERROR});
				}
			});
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>