<div id="dialog-form" title="<?php echo $this->translate('Add User Group'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>	
</div>

<script type="text/javascript">
//	$("#privilege").multiselect();
	$("#privilege").multiselect(/*{
		noneSelectedText: 'Select Something (required)',
        selectedList: 3,
        classes: 'my-select'
		}*/).multiselectfilter();
		
	com.em.UserGroup.prototype.dialogButtons = {
			'<?php echo $this->translate('Save'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'UserGroup', 'action'=>'create-save'));?>',
				type: "POST", 
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						com.em.UserGroup.prototype.flashError('<?php echo _("The form contains error and is not saved");?>', {header: com.em.Alert.ERROR});
						return false;
					}
					
					com.em.UserGroup.prototype.processingDisplay(true);
					return true;
				},
				
				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.UserGroup.prototype.flashSuccess(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.name_duplicate) {
								$("#name").parent().find('.error').remove();
								$("#name").parent().append('<label class="error" for="name" generated="true">'+data.message+'</label>');
							} else {
								var name = data.messageArray.name;
								var privilege = data.messageArray.privilege;
								
								if (name != undefined) {
									$('#name').parent().find('.error').remove();
									$('#name').parent().append('<label class="error" for="name" generated="true">'+name.isEmpty+'</label>');
								}

								if (privilege != undefined) {
									$('#privilege').parent().find('.error').remove();
									$('#privilege').parent().append('<label class="error" for="privilege" generated="true">'+privilege.isEmpty+'</label>');
								}
							}
							com.em.UserGroup.prototype.flashError(data.message, {header: com.em.Alert.ERROR});
						}
					}
				},
				
				complete: function(jqXHR, textStatus) {
					com.em.UserGroup.prototype.processingDisplay(false);
					
				},
				
				error: function(jqXHR, textStatus, errorThrown) {
					dialogFormEducationLevel.dialog('close');
					com.em.UserGroup.prototype.flashError(errorThrown,{header: com.em.Alert.ERROR});
				}
			});
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>