<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/ajax-upload/ajaxupload.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Pathfinder.js","text/javascript");?>

<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _("Filter Pathfinder"));?>
	<div id="containerFormFilter">
	</div>
	<br>
	<?php echo $this->tableHeader('pathfinderHeader', _("Pathfinders"));?>
	<?php echo $this->tableList("tblPathfinder");?>	
	<div class="buttons right">
		<?php echo $this->buttonRemove("delete-pathfinder", $this->translate('Remove'), $this->url(array('action'=>'delete')));?>
		<?php echo $this->buttonAdd("create-pathfinder", $this->translate('Add'), $this->url(array('action'=>'create')));?>
	</div>
		
	<div id="dialog"></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		var managerial = new com.em.Pathfinder();
		
		// network
		managerial.setUrl({
			toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
			toBase : '<?php echo $this->baseUrl(); ?>',
			toUpdate : '<?php echo $this->url(array('action'=>'update')); ?>'
		});
		
		var headers = new Object();
		headers.headerArray = new Array(
			'<?php echo $this->translate('Firstname'); ?>',
			'<?php echo $this->translate('Lastname'); ?>',
			'<?php echo $this->translate('Mobile'); ?>',
			'<?php echo $this->translate('Changed'); ?>');
		managerial.setHeaders(headers);
		// configuration of widgets
		managerial.configureTable('#tblPathfinder', true);
		
		// CRUD
		managerial.clickToAdd('#create-pathfinder');
		managerial.clickToUpdate('#tblPathfinder a[id^=update-pathfinder-]');
		managerial.clickToDelete('#delete-pathfinder');
	});
</script>