<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-lightbox/js/jquery.lightbox-0.5.min.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-lightbox/css/jquery.lightbox-0.5.css");?>

<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.timers-1.2.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.easing.1.3.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.galleryview-3.0-dev.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/galleryView/css/jquery.galleryview-3.0-dev.css");?>
<div id="page-title">
	<span class="title">Noticias JA</span>
	<span class="subtitle">Todas las noticias de JA lo encontrara aqui.</span>
</div>

<!-- Posts -->
<div id="posts" class="single">
	<!-- post -->
	<div class="post">
		<h1><a href="#"><?php //echo $this->news->getTitle();?></a></h1>
		<!-- shadow -->
		<div class="thumb-shadow">
			<!-- post-thumb -->
			<ul id="myGallery2">
        <?php foreach ($this->pictures as $picture) {?>
			<li><img data-frame="<?php echo $picture->getSrcCrop() . $picture->getFilenameCrop();?>" src="<?php echo $picture->getSrc() . $picture->getFilename();?>" title="<?php echo $picture->getTitle();?>" data-description="<?php echo $picture->getDescription();?>"/></li>
        <?php }?>
        </ul>
			<div class="post-thumbnail" id="gallery">
				<ul>
					<li>
						<a href="/image/upload/news/<?php //echo $this->news->getImagename();?>" title="<?php //echo $this->news->getTitle();?>">
						<img src="/image/upload/news/<?php //echo //$this->news->getImagename();?>" width="596" height="270"/>
						</a>
					</li>
				</ul>
			</div>
			<!-- ENDS post-thumb -->
			<div>
				<p><?php //echo $this->news->getSummary();?></p>
				<?php //echo $this->news->getContain();?>
			</div>
		</div>
		<!-- ENDS shadow -->

		<!-- meta -->
		<ul class="meta">
			<li><strong>Fecha de publicación</strong> <?php //echo $this->news->getNewsdate();?> </li>
			<li><strong>Escrito por</strong> <a href="#"><?php //echo $this->news->getFount();?></a></li>
<!-- 			<li> <strong>Posted in</strong> -->
<!-- 				<div class="meta-tags"> -->
<!-- 					<a href="#">Webdesign</a> -->
<!-- 					<a href="#">Code</a> -->
<!-- 					<a href="#">Photo</a> -->
<!-- 					<a href="#">Blue</a> -->
<!-- 					<a href="#">Computers</a> -->
<!-- 					<a href="#">Sites</a> -->
<!-- 				</div> -->
<!-- 			</li> -->
		</ul>
		<!-- ENDS meta -->

	</div>
	<!-- ENDS post -->
</div>
<!-- ENDS Posts -->

<!-- sidebar -->
<ul id="sidebar">
	<li>
	<h6>Categories</h6>
		<ul>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
		</ul>
	</li>

	<li>
	<h6>Archives</h6>
		<ul>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
		</ul>
	</li>
</ul>

<script type="text/javascript">
	$(function() {
		$('#gallery a').lightBox();

		$('#myGallery2').galleryView({
			transition_speed: 1000,
			transition_interval: 2000,
			easing: 'swing',
			show_panels: true,
			show_panel_nav: true,
			enable_overlays: true,

			panel_width: 800,
			panel_height: 400,
			panel_animation: 'slide',
			panel_scale: 'crop',
			overlay_position: 'bottom',
			pan_images: true,
			pan_style: 'drag',
			pan_smoothness: 15,
			start_frame: 1,
			show_filmstrip: true,
			show_filmstrip_nav: true,
			enable_slideshow: true,
			autoplay: true,
			show_captions: true,
			filmstrip_size: 3,
			filmstrip_style: 'scroll',
			filmstrip_position: 'bottom',
			frame_width: 164,
			frame_height: 80,
			frame_opacity: 0.5,
			frame_scale: 'crop',
			frame_gap: 5,
			show_infobar: true,
			infobar_opacity: 1
			});
	});


</script>