<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.timers-1.2.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.easing.1.3.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.galleryview-3.0-dev.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/galleryView/css/jquery.galleryview-3.0-dev.css");?>

<div id="page-title">
	<span class="title">Club Alas de Orion</span>
	<span class="subtitle">Club de Conquistadores de la Iglesia "Roca Eterna".</span>
</div>

<ul id="myGallery2">
	<?php foreach ($this->pictures as $picture) {?>
	<li><img data-frame="<?php echo $picture->getSrcCrops() . $picture->getFile()->getFilename();?>" src="<?php echo $picture->getSrc() . $picture->getFile()->getFilename();?>" title="<?php echo $picture->getTitle();?>" data-description="<?php echo $picture->getDescription();?>"/></li>
	<?php }?> 
</ul>

<script type="text/javascript">
	$('#myGallery2').galleryView({
		transition_speed: 1000,
		transition_interval: 2000,
		easing: 'swing',
		show_panels: true,
		show_panel_nav: true,
		enable_overlays: true,
		
		panel_width: 800,
		panel_height: 400,
		panel_animation: 'slide',
		panel_scale: 'crop',
		overlay_position: 'bottom',
		pan_images: true,
		pan_style: 'drag',
		pan_smoothness: 15,
		start_frame: 1,
		show_filmstrip: true,
		show_filmstrip_nav: true,
		enable_slideshow: true,
		autoplay: true,
		show_captions: true,	
		filmstrip_size: 3,
		filmstrip_style: 'scroll',
		filmstrip_position: 'bottom',
		frame_width: 164,
		frame_height: 80,
		frame_opacity: 0.5,
		frame_scale: 'crop',
		frame_gap: 5,
		show_infobar: true,
		infobar_opacity: 1
	});
</script>