<div id="page-title">
	<span class="title"><?php echo $this->title;?></span>
	<span class="subtitle"><?php echo $this->subTitle;?></span>
</div>

<!-- filter -->
<ul id="portfolio-filter" class="filter">
	<li>Filter</li>
	<li><a href="#" rel="all" > All </a></li>
	<li><a href="#" rel="pink" > Pink </a></li>
	<li><a href="#" rel="blue" > Blue </a></li>
	<li><a href="#" rel="green" > Green </a></li>
</ul>
<!-- ENDS filter -->

<!-- gallery-->
<ul id="portfolio-list" class="gallery three-cols">
	<li class="pink"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="pink"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="pink"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="blue"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="blue"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="blue"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="blue"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="green"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="green"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="green"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="green"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
	<li class="green"><a href="img/dummies/282x267.gif" rel="group1" class="fancybox" title="Lorem ipsum dolor"><img src="img/dummies/282x267.gif" alt="Pic"></a></li>
</ul>
<!-- ENDS gallery -->

<!-- pagination -->
<div class="clear"></div>
<ul class='pager'>
	<li class='first-page'><a href='#'>&laquo;</a></li>
	<li><a href='#' >&lsaquo;</a></li>
	<li><a href='#' >2</a></li>
	<li><a href='#' >3</a></li>
	<li class='active'><a href='#'>4</a></li>
	<li><a href='#' >5</a></li>
	<li><a href='#' >6</a></li>
	<li><a href='#' >&rsaquo;</a></li>
	<li class='last-page'><a href='#'>&raquo;</a></li>
</ul>
<!-- ENDS pagination -->