<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.timers-1.2.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.easing.1.3.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.galleryview-3.0-dev.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/galleryView/css/jquery.galleryview-3.0-dev.css");?>

<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/nivo-slider/jquery.nivo.slider.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/nivo-slider/themes/default/default.css");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/nivo-slider/nivo-slider.css");?>
<div id="page-title">
	<span class="title">Club Leon de Juda</span>
	<span class="title"><?php echo _('Club');?> <?php echo $this->nameClub;?></span>
	<span class="subtitle">Club de Conquistadores de la Iglesia "El Fuerte".</span>
</div>

<ul id="myGallery">
<?php foreach ($this->pictures as $picture) {?>
	<?php $srcCrop = sprintf('%s%s', $picture->getSrcCrop(), $picture->getFilenameCrop()); $src = sprintf('%s%s', $picture->getSrc(), $picture->getFilename());?>
	<li><img data-frame="<?php echo $srcCrop;?>" src="<?php echo $src;?>" title="<?php echo $picture->getTitle();?>" data-description="<?php echo $picture->getDescription();?>"/></li>
<?php }?>
</ul>
<br>

<!-- 1/4 cols -->
<div class="three-fourth ">
	<h6 class="line-divider">Three fourths</h6>
	<div id="posts">
		<div class="slider-wrapper theme-default">
			<div id="slider" class="nivoSlider">
			<?php foreach ($this->pictures as $picture) {?>
				<?php $src = sprintf('%s%s', $picture->getSrc(), $picture->getFilename());?>
				<img src="<?php echo $src;?>" data-thumb="<?php echo $src;?>" alt="" title="<?php echo $picture->getTitle();?>"/>
			<?php }?>
			</div>
		</div>
	</div>
</div>
<div class="one-fourth last">
	<!-- sidebar -->
	<ul id="sidebar">
		<!-- init sidebar -->
		<li>
			<h6>Categories</h6>
			<ul>
				<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'profile', 'pageId'=>'leon'));?>" title="<?php echo _('Club Profile')?>"><?php echo _('Club Profile')?></a></li>
				<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'gallerypicture', 'pageId'=>'leon'));?>" title="<?php echo _('Gallery Pictures')?>"><?php echo _('Gallery Pictures')?></a></li>
				<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'galleryvideo', 'pageId'=>'leon'));?>" title="<?php echo _('Gallery Videos')?>"><?php echo _('Gallery Videos')?></a></li>
			</ul>
		</li>

		<li>
			<h6><?php echo _('Members')?></h6>
			<ul>
				<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'directive', 'pageId'=>'leon'));?>" title="<?php echo _('Directive Club Leon de Juda')?>"><?php echo _('Directive Club Leon de Juda')?></a></li>
				<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'member', 'pageId'=>'leon'));?>" title="<?php echo _('Members Club Leon de Juda')?>"><?php echo _('Members Club Leon de Juda')?></a></li>
			</ul>
		</li>
		<!-- ENDS init sidebar -->
	</ul>
	<!-- ENDS sidebar -->
</div>
<div class="clear "></div>
<!-- ENDS 1/4 cols -->

<!-- TABS -->
<!-- the tabs -->
<ul class="tabs">
	<li><a href="#"><span>Featured Pages</span></a></li>
	<li><a href="#"><span>Information</span></a></li>
	<li><a href="#"><span>Recent posts</span></a></li>
</ul>

<!-- tab "panes" -->
<div class="panes">

	<!-- Posts -->
	<div>
		<ul class="blocks-thumbs thumbs-rollover">
			<li>
				<a href="single.html" class="thumb" title="An image"><img src="img/dummies/282x150.gif" alt="Post" /></a>
				<div class="excerpt">
					<a href="single.html" class="header">Lorem ipsum dolor</a>
					Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
				</div>
				<a href="single.html" class="link-button"><span>Read more &#8594;</span></a>
			</li>
			<li>
				<a href="single.html" class="thumb" title="An image"><img src="img/dummies/282x150.gif" alt="Post" /></a>
				<div class="excerpt">
					<a href="single.html" class="header">Lorem ipsum dolor</a>
					Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
				</div>
				<a href="single.html" class="link-button"><span>Read more &#8594;</span></a>
			</li>
			<li>
				<a href="single.html" class="thumb" title="An image"><img src="img/dummies/282x150.gif" alt="Post" /></a>
				<div class="excerpt">
					<a href="single.html" class="header">Lorem ipsum dolor</a>
					Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
				</div>
				<a href="single.html" class="link-button"><span>Read more &#8594;</span></a>
			</li>
		</ul>
	</div>
	<!-- ENDS posts -->

	<!-- Information  -->
	<div>
		<div class="plain-text">
			<h6>Pellentesque habitant morbi tristique senectus et netus et malesuada.</h6>
			<p>Fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus. </p>
			<p>Fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus.Fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper <a href="single.html">This is a link</a>. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus. </p>
			<a href="single.html" class="link-button"><span>Read more &#8594;</span></a>
		</div>
	</div>
	<!-- ENDS Information -->

	<!-- Posts -->
	<div>
		<ul class="blocks-thumbs thumbs-rollover">
			<li>
				<a href="single.html" class="thumb" title="An image"><img src="img/dummies/282x150.gif" alt="Post" /></a>
				<div class="excerpt">
					<a href="single.html" class="header">Lorem ipsum dolor</a>
					Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
				</div>
				<a href="single.html" class="link-button"><span>Read more &#8594;</span></a>
			</li>
			<li>
				<a href="single.html" class="thumb" title="An image"><img src="img/dummies/282x150.gif" alt="Post" /></a>
				<div class="excerpt">
					<a href="single.html" class="header">Lorem ipsum dolor</a>
					Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
				</div>
				<a href="single.html" class="link-button"><span>Read more &#8594;</span></a>
			</li>
			<li>
				<a href="single.html" class="thumb" title="An image"><img src="img/dummies/282x150.gif" alt="Post" /></a>
				<div class="excerpt">
					<a href="single.html" class="header">Lorem ipsum dolor</a>
					Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
				</div>
				<a href="single.html" class="link-button"><span>Read more &#8594;</span></a>
			</li>
		</ul>
	</div>
	<!-- ENDS posts -->


</div>
<!-- ENDS TABS -->

<script type="text/javascript">
	$('#myGallery').galleryView({
		transition_speed: 1000,
		transition_interval: 2000,
		easing: 'swing',
		show_panels: true,
		show_panel_nav: true,
		enable_overlays: true,

		panel_width: 955,
		panel_height: 450,
		panel_animation: 'slide',
		panel_scale: 'crop',
		overlay_position: 'bottom',
		pan_images: true,
		pan_style: 'drag',
		pan_smoothness: 15,
		start_frame: 1,
		show_filmstrip: true,
		show_filmstrip_nav: true,
		enable_slideshow: true,
		autoplay: true,
		show_captions: true,
		filmstrip_size: 3,
		filmstrip_style: 'scroll',
		filmstrip_position: 'bottom',
		frame_width: 164,
		frame_height: 80,
		frame_opacity: 0.5,
		frame_scale: 'crop',
		frame_gap: 5,
		show_infobar: true,
		infobar_opacity: 1
	});

	$('#slider').nivoSlider();

	$("ul.tabs").tabs("div.panes > div", {effect: 'fade'});
</script>