<div id="dialog-form" title="<?php echo $this->translate('Edit Directive'); ?>" class="header" style="display: none;">
	<?php echo $this->form;?>
</div>

<script type="text/javascript">
	com.em.DirectiveGuest.prototype.dialogButtons = {
		'<?php echo $this->translate('Update'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'Directive', 'action'=>'update-save')); ?>',
				type: "POST",
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						com.em.Directive.prototype.flashError('<?php echo _("The form contains error and is not updated");?>', {header: com.em.Alert.ERROR});
						return false;
					}

					com.em.Directive.prototype.processingDisplay(true);
					return true;
				},

				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.Directive.prototype.flashSuccess(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							com.em.Directive.prototype.flashError(data.message, {header: com.em.Alert.ERROR});
						}
					}
				},

				complete: function(jqXHR, textStatus) {
					com.em.Directive.prototype.processingDisplay(false);
				},

				error: function(jqXHR, textStatus, errorThrown) {
					dialogForm.dialog('close');
					com.em.Directive.prototype.flashError(errorThrown, {header: com.em.Alert.ERROR});
				}
			});
		},

		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>