<div id="dialog-form" title="<?php echo $this->translate('Add Managerial'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>	
</div>

<script type="text/javascript">	
	com.em.Managerial.prototype.dialogButtons = {
			'<?php echo $this->translate('Save'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'managerial', 'action'=>'create-save'));?>',
				type: "POST", 
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						com.em.Managerial.prototype.flashError('<?php echo _("The form contains error and is not saved");?>', {header: com.em.Alert.ERROR});
						return false;
					}
					
					com.em.Managerial.prototype.processingDisplay(true);
					return true;
				},
				
				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.Managerial.prototype.flashSuccess(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.identityCard_duplicate) {
								$("#identityCard").parent().find('.error').remove();
								$("#identityCard").parent().append('<label class="error" for="identityCard" generated="true">'+data.message+'</label>');
							} else {
								var firstName = data.messageArray.firstName;
								var lastName = data.messageArray.lastName;
								var identityCard = data.messageArray.identityCard;
								var sex = data.messageArray.sex;
								var username = data.messageArray.username;
								var password = data.messageArray.password;
								var passwordConfirm = data.messageArray.passwordConfirm;
								var email = data.messageArray.email;
								var phonemobil = data.messageArray.phonemobil;
								
								if (firstName != undefined) {
									$('#firstName').parent().find('.error').remove();
									$('#firstName').parent().append('<label class="error" for="firstName" generated="true">'+firstName.isEmpty+'</label>');
								}

								if (lastName != undefined) {
									$('#lastName').parent().find('.error').remove();
									$('#lastName').parent().append('<label class="error" for="lastName" generated="true">'+lastName.isEmpty+'</label>');
								}

								if (identityCard != undefined) {
									$('#identityCard').parent().find('.error').remove();
									$('#identityCard').parent().append('<label class="error" for="identityCard" generated="true">'+identityCard.isEmpty+'</label>');
								}

								if (identityCard != undefined) {
									if (identityCard.isEmpty != undefined) {
										$('#identityCard').parent().find('.error').remove();
										$('#identityCard').parent().append('<label class="error" for="identityCard" generated="true">'+identityCard.isEmpty+'</label>');	
									}
									
									if (identityCard.notBetween != undefined) {
										$('#identityCard').parent().find('.error').remove();
										$('#identityCard').parent().append('<label class="error" for="identityCard" generated="true">'+identityCard.notBetween+'</label>');
									}

									if (identityCard.notDigits != undefined) {
										$('#identityCard').parent().find('.error').remove();
										$('#identityCard').parent().append('<label class="error" for="identityCard" generated="true">'+identityCard.notDigits+'</label>');
									}
								}

								if (sex != undefined) {
									$('#sex').parent().find('.error').remove();
									$('#sex').parent().append('<label class="error" for="sex" generated="true">'+sex.isEmpty+'</label>');
								}

								if (username != undefined) {
									$('#username').parent().find('.error').remove();
									$('#username').parent().append('<label class="error" for="username" generated="true">'+username.isEmpty+'</label>');
								}

								if (password != undefined) {
									$('#password').parent().find('.error').remove();
									$('#password').parent().append('<label class="error" for="password" generated="true">'+password.isEmpty+'</label>');
								}

								if (passwordConfirm != undefined) {
									$('#passwordConfirm').parent().find('.error').remove();
									$('#passwordConfirm').parent().append('<label class="error" for="passwordConfirm" generated="true">'+passwordConfirm.isEmpty+'</label>');
								}

								if (email != undefined) {
									if (email.isEmpty != undefined) {
										$('#email').parent().find('.error').remove();
										$('#email').parent().append('<label class="error" for="email" generated="true">'+email.isEmpty+'</label>');	
									}

									if (email.emailAddressInvalidFormat != undefined) {
										$('#email').parent().find('.error').remove();
										$('#email').parent().append('<label class="error" for="email" generated="true">'+email.emailAddressInvalidFormat+'</label>');
									}
								}

								if (phonemobil != undefined) {
									if (phonemobil.isEmpty != undefined) {
										$('#phonemobil').parent().find('.error').remove();
										$('#phonemobil').parent().append('<label class="error" for="phonemobil" generated="true">'+phonemobil.isEmpty+'</label>');
									}

									if (phonemobil.notDigits != undefined) {
										$('#phonemobil').parent().find('.error').remove();
										$('#phonemobil').parent().append('<label class="error" for="phonemobil" generated="true">'+phonemobil.notDigits+'</label>');
									}									
								}
							}
							com.em.Managerial.prototype.flashError(data.message, {header: com.em.Alert.ERROR});
						}
					}
				},
				
				complete: function(jqXHR, textStatus) {
					com.em.Managerial.prototype.processingDisplay(false);
					
				},
				
				error: function(jqXHR, textStatus, errorThrown) {
					dialogForm.dialog('close');
					com.em.Managerial.prototype.flashError(errorThrown,{header: com.em.Alert.ERROR});
				}
			});
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>