<div id="dialog-form" title="<?php echo $this->translate('Edit Managerial'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
	com.em.Managerial.prototype.dialogButtons = {
		'<?php echo $this->translate('Update'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'managerial', 'action'=>'update-save')); ?>',
				type: "POST",
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						com.em.Managerial.prototype.flashError('<?php echo _("The form contains error and is not updated");?>', {header: com.em.Alert.ERROR});
						return false;
					}

					com.em.Managerial.prototype.processingDisplay(true);
					return true;
				},
				
				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.Managerial.prototype.flashSuccess(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.identityCard_duplicate) {
								$("#identityCard").parent().find('.error').remove();
								$("#identityCard").parent().append('<label class="error" for="identityCard" generated="true">'+data.message+'</label>');
							} else {
								var identityCard = data.messageArray.identityCard;
								
								if (identityCard != undefined) {
									$('#identityCard').parent().find('.error').remove();
									$('#identityCard').parent().append('<label class="error" for="identityCard" generated="true">'+identityCard.isEmpty+'</label>');
								}
							}
							com.em.Managerial.prototype.flashError(data.message, {header: com.em.Alert.ERROR});
						}
					}
				},
				
				complete: function(jqXHR, textStatus) {
					com.em.Managerial.prototype.processingDisplay(false);
				},
				
				error: function(jqXHR, textStatus, errorThrown) {
					dialogForm.dialog('close');
					com.em.Managerial.prototype.flashError(errorThrown,{header: com.em.Alert.ERROR});
				}
			});
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>