<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Country.js","text/javascript");?>
<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _("Filter Country"));?>
	<div id="containerFormFilter">
		<?php echo $this->formFilter; ?>
	</div>
	<br>
	<?php echo $this->tableHeader('countryHeader', _("Countries"));?>
	<?php echo $this->tableList("tblCountry");?>	
	<div class="buttons right">
		<?php echo $this->buttonRemove("delete-country", $this->translate('Remove'), $this->url(array('action'=>'delete')));?>
		<?php echo $this->buttonAdd("create-country", $this->translate('Add'), $this->url(array('action'=>'create')));?>
	</div>
		
	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	var country = new com.em.Country();
			
	// network
	country.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'update')); ?>'
	});
	
	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Name'); ?>',
		'<?php echo $this->translate('Description'); ?>',
		'<?php echo $this->translate('Created'); ?>',
		'<?php echo $this->translate('Changed'); ?>');
	country.setHeaders(headers);
	// configuration of widgets
	country.configureTable('#tblCountry', true);
	
	// CRUD
	country.clickToAdd('#create-country');
	country.clickToUpdate('#tblCountry a[id^=update-country-]');
	country.clickToDelete('#delete-country');
});
</script>