<div class="sidebar">
	<h2>Latest Blog</h2>
	<div class="sidebar_item">
		<h4>March 2012</h4>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
		<div class="button_small">
	    <a href="#">Read more</a>
	    </div><!--close button_small-->
	</div><!--close sidebar_item-->
</div><!--close sidebar-->
	
<div class="sidebar">
   	<h2>Latest Blog</h2>
	<div class="sidebar_item">
		<h4>March 2012</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
		<div class="button_small">
		<a href="#">Read more</a>
	    </div><!--close button_small-->
	</div><!--close sidebar_item--> 
</div><!--close sidebar-->  

<div class="sidebar">
	<h2>Latest Blog</h2>
	<div class="sidebar_item">
		<h4>March 2012</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
		<div class="button_small">
			<a href="#">Read more</a>
		</div><!--close button_small-->
	</div><!--close sidebar_item--> 
</div><!--close sidebar-->