<?php 
	if ($this->pageCount): ?>  
    <ol class="pagination">  
    <!-- Previous page link -->  
    <?php if (isset($this->previous)): ?>  
		<li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">Previous</a></li>
	<?php else: ?>
	<?php endif; ?>  
   	<!-- Numbered page links -->  
   	<?php foreach ($this->pagesInRange as $page): ?>  
    <?php if ($page != $this->current): ?>  
       	<li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>  
	<?php else: ?>  
    	<li class="selected"><a href="#"><?php echo $page; ?></a></li>  
	<?php endif; ?>  
	<?php endforeach; ?>  
   <!-- Next page link -->  
   	<?php if (isset($this->next)): ?>  
     	<li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">Next</a></li>  
   	<?php else: ?><?php endif; ?>  
   	</ol>  
   	<?php endif; ?>
   	