<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/tinymce/jscripts/tiny_mce/jquery.tinymce.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/tinymce/jscripts/tiny_mce/tiny_mce.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/multiple-file-upload/jquery.form.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/multiple-file-upload/jquery.MetaData.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/multiple-file-upload/jquery.MultiFile.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/multiple-file-upload/jquery.blockUI.js","text/javascript"); ?>

<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/NewsUpdate.js","text/javascript"); ?>
<div class="card">
	<?php echo $this->form; ?>
	<div class="buttons left" style="padding-left: 500px;">	
		<a class="green buttonNg" id="save-news" style="float: right"> 
			<span class="left"></span>
			<div>
				<?php echo $this->translate('Save'); ?>
			</div>
			<span class="right"></span> 
		</a>
	</div>
</div>	

<script type="text/javascript">
	$(document).ready(function() {		
		var news = new com.em.NewsUpdate();
		news.configureTinymce('textarea.contain');
		
		// network
		news.setUrl({
			toUpdate : '<?php echo $this->url(array('module'=>'admin', 'controller'=>'news', 'action'=>'create-save'));?>'
		});
		
		news.clickToUpdate('#save-news');

		$('#imageFile').MultiFile({
			max: 2,
			accept: 'gif|jpg|png'
//			STRING: {
//				remove:'Remover',
//				selected:'Selecionado: $file',
//				denied:'Invalido arquivo de tipo $ext!'
//				}			
		});
					
	});
</script>