<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/tinymce/jscripts/tiny_mce/jquery.tinymce.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/tinymce/jscripts/tiny_mce/tiny_mce.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/HelpTextUpdate.js","text/javascript"); ?>
<div class="card">
	<?php echo $this->form; ?>
</div>	

<script type="text/javascript">
	$('textarea.contain').tinymce({
	// Location of TinyMCE script
	script_url : '../jscripts/tiny_mce/tiny_mce.js',

	// General options
	theme : "advanced",
	plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

	// Theme options
	theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
	theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
	theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
	theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : true,
//
//	// Example content CSS (should be your site CSS)
	content_css : "css/content.css"
//
//	// Drop lists for link/image/media/template dialogs
//	template_external_list_url : "lists/template_list.js",
//	external_link_list_url : "lists/link_list.js",
//	external_image_list_url : "lists/image_list.js",
//	media_external_list_url : "lists/media_list.js",
//
//	// Replace values for the template plugin
//	template_replace_values : {
//		username : "Some User",
//		staffid : "991234"
//	}
	});
	
	function ajaxLoad() {
    	var ed = tinyMCE.get('content');

        // Do you ajax call here, window.setTimeout fakes ajax call
        ed.setProgressState(1); // Show progress
        window.setTimeout(function() {
                ed.setProgressState(0); // Hide progress
                ed.setContent('HTML content that got passed from server.');
        }, 3000);
	}
	
	function saveContent() {
        var tinyObj = tinyMCE.get('contain');
        var htmlContent = tinyObj.getContent();

        $.ajax({
			url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'news', 'action'=>'create-save'));?>',
			type: "POST", 
			dataType: 'json',
			data: $('#formId').serialize(),
			beforeSend: function(XMLHttpRequest) {
				return true;
			},
			
			success: function(data, textStatus, XMLHttpRequest) {
				$(window.location).attr('href', 'http://dist2/admin/news/');
				
				if (textStatus == 'success') {
					if (data.success) {
						
					} else {
						if (data.message == 'name_warning') {
						
						} else {
							
						}
					}
				}
			},
			
			complete: function(jqXHR, textStatus) {
				
			},
			
			error: function(jqXHR, textStatus, errorThrown) {
				
			}
		});
	}
</script>