<div id="dialog-form" title="<?php echo $this->translate('Add News'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>	
</div>

<script type="text/javascript">
	$("#name").bind('keyup', function(e) {
		var nameVal = $('#title').val();
		if (nameVal != '') {
			$("#title").parent().find('.error').remove();
		}
	});
	
	com.em.News.prototype.dialogButtons = {
			'<?php echo $this->translate('Save'); ?>': function() {

//				function PostForm() {
	                  // Set url Action and Controller asp.net MVC
                 var _urlAction = '';
//					("Create","FileUpload") %>';
//	                 var _formData = $("formId").serialize();
//	                 $.post(_urlAction, _formData, PostFormReturn,
//	"json");
//	             } 
//				$('#formId').submit(function() {
//					  alert('Handler for .submit() called.');
//					  return false;
//					});
//			dialogForm.dialog('close');
//			$.ajax({
//				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'news', 'action'=>'create-save'));?>',
//				type: "POST", 
//				dataType: 'json',
//				data: $('#formId').serialize(),
//				beforeSend: function(XMLHttpRequest) {
//					validator.form();
//					if (!validator.valid()) {
//						return false;
//					}
//					
//					com.em.News.prototype.processingDisplay(true);
//					return true;
//				},
//				
//				success: function(data, textStatus, XMLHttpRequest) {
//					if (textStatus == 'success') {
//						if (data.success) {
//							dialogForm.dialog('close');
//							table.fnDraw();
//							com.em.News.prototype.showAlert(data.message, {header: com.em.Alert.SUCCESS});
//						} else {
//							if (data.message == 'name_warning') {
//							
//							} else {		
//								$("#name").parent().find('.error').remove();	
//
//								$("#name").parent().append('<ul id="error-name" class="error"><li>'+data.message+'</li> </ul>');						
//								com.em.News.prototype.showAlert(data.message, {header: com.em.Alert.ERROR});
//							}
//						}
//					}
//				},
//				
//				complete: function(jqXHR, textStatus) {
//					com.em.News.prototype.processingDisplay(false);
//					
//				},
//				
//				error: function(jqXHR, textStatus, errorThrown) {
//					dialogForm.dialog('close');
//					com.em.News.prototype.showAlert(errorThrown,{header : com.em.Alert.ERROR});
//				},
//				
//				getErrorHtml: function() {
//					for ( var id in data.message) {
//						$("#"+id).parent().find('.error').remove();									
//			    	    $("#"+id).parent().append('<ul id="errors-name" class="error"><li>'+data.message.name.emailAddressInvalidFormat+'</li> </ul>');
//					}	
//				}
//			});
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>