
<div class="section-teaser featured">
	<div class="featured-inner">
	<div class="window">
	<script type="text/javascript">
		function toggleBoxes(source) {
			var objCheckBoxes = document.forms['form'].elements['id[]'];
			// set the check value for all check boxes
			for(var i = 0; i < objCheckBoxes.length; i++)
				objCheckBoxes[i].checked = source.checked;
		}
	
		function enviar_formulario(){
			   document.forms['form'].submit();
		} 
	</script>	      
		<form action = "<?php echo $this->url(array('controller'=>'news', 'action'=>'remove'));?>" method="post" name="form">  
			<table class="zebralist">
				<thead>
				<tr>
				    <th>Title</th>
				    <th>summary</th>
				    <th>Contain</th>
				    <th>Fount</th>
				    <th>News Date</th>
				    <th><input type="checkbox" onclick="toggleBoxes(this);"/></th>
				</tr>
				</thead>
				<?php $i = 0; $nameClass = "";?>
				<?php foreach($this->news as $newsItem) : ?>
				<?php if ($i % 2 == 0)$nameClass = 'class = "zebrastripe"'; else $nameClass = ""; $i++;?>
				<tr <?php echo $nameClass?>>
					<td> <a href="<?php echo $this->url(array('controller'=>'news', 'action'=>'edit', 'id'=>$newsItem->newsId));?>"><?php echo $this->escape($newsItem->title);?></a>
			    	<td><?php echo $this->escape($newsItem->summary);?></td>
			    	<td><?php echo $this->escape($newsItem->contain);?></td>
			    	<td><?php echo $this->escape($newsItem->fount);?></td>
			    	<td><?php echo $this->escape($newsItem->newsdate);?></td>
			    	<td> <input type="checkbox" value= "<?php echo $newsItem->newsId;?>" name = "id[]"> </td>
				</tr>
				<?php endforeach; ?>
			</table>
			<div class="listing-footer">
    			<?php  echo $this->paginationControl($this->news, 'Sliding', 'pagination/pagination_control.phtml'); ?>
  				<div class="num-results">
    			Results <strong>1</strong>–<strong>20</strong> of <strong>69</strong>
    			</div>
			</div>
			
			<p><a href="<?php echo $this->url(array('controller'=>'news', 'action'=>'add'));?>">Add</a></p> 
			<br>
			<p><a href="<?php echo $this->url(array('controller'=>'news', 'action'=>'remove'));?>">Remove</a></p>
			<br>
			<input type="submit" value="Remove">
		</form>
	</div>
	</div>
</div>