<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/News.js","text/javascript");?>
<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _("Filter News"));?>
	<div id="containerFormFilter">
		<?php echo $this->formFilter; ?>
	</div>
	<br>
	<?php echo $this->tableHeader('newsHeader', _("News"));?>
	<?php echo $this->tableList("tblNews");?>	
	<div class="buttons right">
		<?php echo $this->buttonRemove("delete-news", $this->translate('Remove'), $this->url(array('action'=>'delete')));?>
		<?php echo $this->buttonAdd("create-news", $this->translate('Add'), $this->url(array('action'=>'create')));?>
	</div>
		
	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	var news = new com.em.News();
		
	// network
	news.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'update')); ?>'
	});
	
	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Title'); ?>',
		'<?php echo $this->translate('Summary'); ?>',
		'<?php echo $this->translate('Category'); ?>',
		'<?php echo $this->translate('Created'); ?>',
		'<?php echo $this->translate('Changed'); ?>');
	news.setHeaders(headers);
	// configuration of widgets
	news.configureTable('#tblNews', true);
	
	// CRUD
	news.clickToAdd('#create-news');
	news.clickToUpdate('#tblNews a[id^=update-news-]');
	news.clickToDelete('#delete-news');
});
</script>