<div id="dialog-form" title="<?php echo $this->translate('Edit Department'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
	com.em.News.prototype.dialogButtons = {
		'<?php echo $this->translate('Update'); ?>': function() {
			validator.form();
			if (!validator.valid()) {
				return false;
			}
			$('#submit').click();
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>