<div id="dialog-form" title="<?php echo $this->translate('Add Country'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>	
</div>
<div style="background-color: blue;">
</div>
<script type="text/javascript">
//	$("#name").bind('keyup', function(e) {
//		var nameVal = $('#name').val();
//		if (nameVal != '') {
//			$("#name").parent().find('.error').remove();
//		}
//	});
	
	com.em.Country.prototype.dialogButtons = {
			'<?php echo $this->translate('Save'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'country', 'action'=>'create-save'));?>',
				type: "POST", 
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						return false;
					}
					
					com.em.Country.prototype.processingDisplay(true);
					return true;
				},
				
				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.Country.prototype.showAlert(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.message == 'name_warning') {
							
							} else {		
								$("#name").parent().find('.error').remove();	

								$("#name").parent().append('<ul id="error-name" class="error"><li>'+data.message+'</li> </ul>');						
								com.em.Country.prototype.showAlert(data.message, {header: com.em.Alert.ERROR});
							}
						}
					}
				},
				
				complete: function(jqXHR, textStatus) {
					com.em.Country.prototype.processingDisplay(false);
					
				},
				
				error: function(jqXHR, textStatus, errorThrown) {
					dialogForm.dialog('close');
					com.em.Country.prototype.showAlert(errorThrown,{header : com.em.Alert.ERROR});
				},
				
				getErrorHtml: function() {
					for ( var id in data.message) {
						$("#"+id).parent().find('.error').remove();									
			    	    $("#"+id).parent().append('<ul id="errors-name" class="error"><li>'+data.message.name.emailAddressInvalidFormat+'</li> </ul>');
					}	
				}
			});
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>