<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ImageDataVaultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageDataVaultRepository extends EntityRepository {

	public function findByCriteria($filters = array(), $limit = NULL, $offset = NULL) {
		$query = $this->_em->createQueryBuilder();

		$query->select('images')->from($this->_entityName, 'images');

		return $query->getQuery()->getResult();
	}
}