<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PictureTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureTypeRepository extends EntityRepository
{
}