<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PictureCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureCategoryRepository extends EntityRepository {

	/**
	 * (non-PHPdoc)
	 * @see Doctrine\ORM.EntityRepository::findAll()
	 */
	public function findAll() {
		return $this->findBy(array('state' => TRUE));
	}
}