<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends EntityRepository {

	public function findByCriteria($filters = array(), $limit = NULL, $offset = NULL) {
		$query = $this->_em->createQueryBuilder();

		$query
			->add('select', 'positions')
			->add('from', 'Model\Position positions');

		return $query->getQuery()->getResult();
	}

	/**
	 * (non-PHPdoc)
	 * @see Doctrine\ORM.EntityRepository::findAll()
	 */
	public function findAll() {
		return $this->findBy(array('state' => 1));
	}
}