<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * UnityClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnityClubRepository extends EntityRepository
{
}