<form id="<?php echo $this->element->getAttrib('id')?>" action="<?php echo $this->element->getAction()?>" method="post" enctype="multipart/form-data">
	<div class="row">
		<div class="span7">
			<label><?php echo _('My picture');?></label>
			<div class="well" id="result" style="width: 127px; height: 127px;">
				<img src="<?php echo $this->element->getSource();?>" id="profile_img" style="width: 127px; height: 127px;"/>
			</div>
		</div>
	</div>
	<table>
		<tbody>
			<tr class="odd" style="height: 20px;">
				<td><?php echo $this->element->getElement('firstName')->renderLabel()?></td>
				<td><div><?php echo $this->element->getElement('firstName')->getValue()?></div></td>
			</tr>
			<tr class="even" style="height: 20px;">
				<td><?php echo $this->element->getElement('lastName')->renderLabel()?></td>
				<td><div><?php echo $this->element->getElement('lastName')->getValue()?></div></td>
			</tr>
			<tr class="odd" style="height: 20px;">
				<td><?php echo $this->element->getElement('sex')->renderLabel() ?></td>
				<td><div><?php echo $this->element->getElement('sex')->getValue() ?></div></td>
			</tr>
			<tr class="even" style="height: 20px;">
				<td><?php echo $this->element->getElement('email')->renderLabel() ?></td>
				<td><div><?php echo $this->element->getElement('email')->getValue() ?></div></td>
			</tr>
			<tr class="odd" style="height: 20px;">
				<td><?php echo $this->element->getElement('phonemobil')->renderLabel() ?></td>
				<td><div><?php echo $this->element->getElement('phonemobil')->getValue() ?></div></td>
			</tr>
			<tr class="even" style="height: 20px;">
				<td><?php echo $this->element->getElement('phone')->renderLabel() ?></td>
				<td><div><?php echo $this->element->getElement('phone')->getValue() ?></div></td>
			</tr>
			<tr class="odd" style="height: 20px;">
				<td><?php echo $this->element->getElement('club')->renderLabel() ?></td>
				<td><div><?php echo $this->element->getElement('club')->getValue() ?></div></td>
			</tr>
			<tr class="even" style="height: 20px;">
				<td><?php echo $this->element->getElement('position')->renderLabel() ?></td>
				<td><div><?php echo $this->element->getElement('position')->getValue() ?></div></td>
			</tr>
		</tbody>
	</table>
</form>