<form id="<?php echo $this->element->getAttrib('id') ?>">
	<table>
		<tbody>
			<tr class="odd" >
				<td><?php echo $this->element->getElement('name')->renderLabel(); ?></td>
				<td><?php echo $this->element->getElement('name')->renderViewHelper(); ?></td>
			</tr>
			<tr class="even" >
				<td><?php echo $this->element->getElement('description')->renderLabel(); ?></td>
				<td><?php echo $this->element->getElement('description')->renderViewHelper(); ?></td>
			</tr>
			<tr class="odd" >
				<td><?php echo $this->element->getElement('module')->renderLabel(); ?></td>
				<td><?php echo $this->element->getElement('module')->renderViewHelper(); ?></td>
			</tr>
			<tr class="even" >
				<td><?php echo $this->element->getElement('controller')->renderLabel(); ?></td>
				<td><?php echo $this->element->getElement('controller')->renderViewHelper(); ?></td>
			</tr>
			<tr class="odd" >
				<td><?php echo $this->element->getElement('action')->renderLabel(); ?></td>
				<td><?php echo $this->element->getElement('action')->renderViewHelper(); ?></td>
			</tr>
		</tbody>
	</table>
	<input type="hidden" value="0" id="duplicateName" name="duplicateName"/>
</form>