<div id="page-title">
	<span class="title">Nuestras creencias</span>
	<span class="subtitle">La Iglesia adventista tiene 6 doctrinas y 28 creencias</span>
</div>

<p>Los Adventistas del 
Séptimo Día aceptan la Biblia como su único credo y mantienen ciertas 
creencias fundamentales como siendo la enseñanza de las Escrituras 
Sagradas. Estas creencias, de la manera como son presentadas aquí, 
constituyen la comprensión de la expresión de la enseñanza de las 
Escrituras por parte de la Iglesia. Puede haber revisiones de estas 
declaraciones en una asamblea de la Asociación General, cuando la 
Iglesia es llevada por el Espíritu Santo a una comprensión más completa 
de la verdad bíblica o encuentra mejor lenguaje para expresar las 
enseñanzas de la Santa Palabra de Dios.</p>
<div class="clear "></div>