<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-lightbox/js/jquery.lightbox-0.5.min.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-lightbox/css/jquery.lightbox-0.5.css");?>

<h2 class="addon">
   	<span><?php echo _('Explication of the logo');?></span>
</h2>
<h4 class="author">by <a href="#"><?php echo _('Union Boliviana')?></a></h4>
<div class="featured">
	<div class="featured-inner object-lead inverse">
		<div id="addon-summary-wrapper">
        	<div id="addon-summary" class="primary">
				<h4>1.- Las Lineas</h4>
	            <p align="justify">Las lineas de arriba del diseño sugieren la resurección y asención de Cristo en la segunda venida, principal foco de nuestra Fé.</p>
	            <h4>2.- La Bilbia abierta</h4>
	            <p align="justify">La Biblia es la base de nuestro diseño y representa el fundamento biblico de nuestras creencias. Esta diseñada en una posición totalmente abierta sugiriendo la completa aceptación de la palabra de Dios.</p>
	            <h4>3.- La Cruz</h4>
	            <p align="justify">El simbolo de la Cruz, representa el avangelio de la salvación, está localizada en el centro del diseño para enfatizar el sacrificio de Cristo, que es el tema central de nuestra Fé.</p>
	            <h4>4.- Las llamas de fuego </h4>
	            <p align="justify">Esté es el formato de tres lineas circulando una esfera implicita, Las lineas representan los tres Ángeles de Apocalipsis 14 circulando el globo terraquio y nuestro compromiso de llevar el evangelio para todo el mundo.</p>
	            <p align="justify"">El formato completo forma una llama simbolica del Espíritu Santo.</p>
				<div style="display: none;" class="hidden">
					<div style="width: 300px;" id="contribute-why" class="popup"></div>
				</div>
        	</div>
        </div>
	</div>        
</div>

<div id="gallery">
    <ul>
        <li>
            <a href="/image/logos/logo-iasd7.png" title="Logo de Iglesia Adventista del septimo dia">
            	<img alt="our logo" src="/image/logos/logo-iasd7.png" width="200" height="190">
            </a>
        </li>
    </ul>
</div>

<script type="text/javascript">
	$(function() {
    	$('#gallery a').lightBox();
	});
</script>