<div id="tabs">
	<ul>
		<?php
		$container = $this->navigation()->getContainer();
		$childPage = $container->findOneBy('active', TRUE);
		if (!$childPage->hasPages()) {
			$parent = $childPage->getParent();	
		} else {
			$parent = $childPage;	
		}
		foreach ($parent as $submenu):?>
			<li>
				<?php $label = $this->translate($submenu->getLabel());?>
				<a class="<?php echo $submenu->isActive() ? "active" : '';?>" href="<?php echo $submenu->getHref();?>" title="<?php echo $label;?>"><span><?php echo $label;?></span></a>
			</li>
		<?php endforeach;?>
	</ul>
</div>
<div class="clear"></div>

