<div id="tabs">
	<ul>
		<?php
		$container = $this->navigation()->getContainer();
		$childPage = $container->findOneBy('active', TRUE);
		$parent = $childPage->getParent();
		foreach ($parent as $submenu):?>
			<li class="<?php echo $submenu->isActive() ? "active" : '';?>">
				<?php $label = $this->translate($submenu->getLabel());?>
				<a href="<?php echo $submenu->getHref();?>" title="<?php echo $label;?>"><span><?php echo $label;?></span></a>
			</li>
		<?php endforeach;?>
	</ul>
</div>
<div class="clear"></div>

