<div id="header">
	<div id="banner">
		<h1><span>Your</span> Business</h1>
	</div><!--close banner-->
	    <h2>Church Slogan Here</h2>
	<div id="menubar">
		<ul id="nav">
		<?php
			$container = $this->navigation()->getContainer();
			$menus = $container->getPages();
			foreach ($menus as $menu):
				$menuActive = $menu;?>
			<li class="<?php echo $menu->isActive() ? "active" : ""; ?>">	
				<a href="<?php echo $menu->getHref();?>" class="top_lik"><?php echo $this->translate($menu->getLabel());?></a>
				<?php if ($menu->hasPages() && $menu->count() > 1) {?>
					<?php $submenus = $menu->getPages(); ?>
				<ul>
				<?php foreach ($submenus as $submenu):?>
					<li><a href="<?php echo $submenu->getHref();?>"><?php echo $this->translate($submenu->getLabel());?></a></li>
				<?php endforeach; ?>
				</ul>
				<?php }?>
			</li>
			<?php endforeach; ?>
		</ul>
	</div><!--close menubar-->
</div><!--close header-->