<?php echo $this->doctype(); ?>
<html>
	<head>
		<?php //echo $this->jQuery(); ?>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>
		<div id="header-meta" class="noprint">
			<?php echo $this->partial('header.phtml'); ?>
		</div>
				
		<div id="actionbar" style="z-index:3;">
			<?php echo $this->partial('actionbar.phtml'); ?>
		</div>
		
		<div id="footer" class="noprint">
			<?php echo $this->partial('footer.phtml'); ?>
		</div>
		
		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>
      	<?php echo $this->navigation()->breadcrumbs(); ?>
		<script type="text/javascript">
      	<?php
      		$messagesArray = $this->messages;
			foreach ($messagesArray as $messages) {
				foreach ($messages as $key => $message) {
					if ($key == 'error') {?>
						this.alert = new com.em.Alert();
						alert.flashError('<?php echo $message; ?>', {header: com.em.Alert.ERROR});
					<?php }
					if ($key == 'success') {?>
						this.alert = new com.em.Alert();
						alert.flashSuccess('<?php echo $message; ?>', {header: com.em.Alert.SUCCESS});
					<?php }
				} 							
			} ?>
      	</script>
	</body>
</html>