<div id="dialog-form" title="<?php echo $this->translate('Add Privilege'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
	com.em.Privilege.prototype.dialogButtons = {
			'<?php echo $this->translate('Save'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'privilege', 'action'=>'create-save'));?>',
				type: "POST",
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						com.em.Privilege.prototype.flashError('<?php echo _("The form contains error and is not saved");?>', {header: com.em.Alert.ERROR});
						return false;
					}

					com.em.Privilege.prototype.processingDisplay(true);
					return true;
				},

				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.Privilege.prototype.flashSuccess(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.name_duplicate) {
								$("#name").parent().find('.error').remove();
								$("#name").parent().append('<label class="error" for="name" generated="true">'+data.message+'</label>');
							} else {
								var name = data.messageArray.name;
								var module = data.messageArray.module;
								var controller = data.messageArray.controller;
								var action = data.messageArray.action;

								if (name != undefined) {
									$('#name').parent().find('.error').remove();
									$('#name').parent().append('<label class="error" for="name" generated="true">'+name.isEmpty+'</label>');
								}

								if (module != undefined) {
									$('#module').parent().find('.error').remove();
									$('#module').parent().append('<label class="error" for="module" generated="true">'+module.isEmpty+'</label>');
								}

								if (controller != undefined) {
									$('#controller').parent().find('.error').remove();
									$('#controller').parent().append('<label class="error" for="controller" generated="true">'+controller.isEmpty+'</label>');
								}

								if (action != undefined) {
									$('#action').parent().find('.error').remove();
									$('#action').parent().append('<label class="error" for="action" generated="true">'+action.isEmpty+'</label>');
								}
							}
							com.em.Privilege.prototype.flashError(data.message, {header: com.em.Alert.ERROR});
						}
					}
				},

				complete: function(jqXHR, textStatus) {
					com.em.Privilege.prototype.processingDisplay(false);

				},

				error: function(jqXHR, textStatus, errorThrown) {
					dialogFormEducationLevel.dialog('close');
					com.em.Privilege.prototype.flashError(errorThrown,{header: com.em.Alert.ERROR});
				}
			});
		},

		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>