<div id="dialog-form" title="<?php echo $this->translate('Add Privilege'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>	
</div>

<script type="text/javascript">	
	com.em.Privilege.prototype.dialogButtons = {
			'<?php echo $this->translate('Save'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'privilege', 'action'=>'create-save'));?>',
				type: "POST", 
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						return false;
					}
					
					com.em.Privilege.prototype.processingDisplay(true);
					return true;
				},
				
				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.Privilege.prototype.showAlert(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.message == 'name_warning') {
							
							} else {
								
//								if (messages.name = undefined) {
//									$('#name').parent().find('.error').remove();
//									$('#name').parent().append('<label class="error" for="name" generated="true">'+data.message+'</label>');
//								}
//								
//								if (messages.module = undefined) {
//									$('#module').parent().find('.error').remove();
//									$('#module').parent().append('<label class="error" for="name" generated="true">'+data.message+'</label>');
//								}
//
//								if (messages.controller = undefined) {
//									$('#controller').parent().find('.error').remove();
//									$('#controller').parent().append('<label class="error" for="name" generated="true">'+data.message+'</label>');
//								}
//								
//								if (messages.action = undefined) {
//									$('#action').parent().find('.error').remove();
//									$('#action').parent().append('<label class="error" for="name" generated="true">'+data.message+'</label>');	
//								}

								$("#name").parent().find('.error').remove();
								$("#name").parent().append('<label class="error" for="name" generated="true">'+data.message+'</label>');						
								com.em.Privilege.prototype.showAlert(data.message, {header: com.em.Alert.ERROR});
							}
						}
					}
				},
				
				complete: function(jqXHR, textStatus) {
					com.em.Privilege.prototype.processingDisplay(false);
					
				},
				
				error: function(jqXHR, textStatus, errorThrown) {
					dialogFormEducationLevel.dialog('close');
					com.em.Privilege.prototype.showAlert(errorThrown,{header : com.em.Alert.ERROR});
				}
			});
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>