<div id="dialog-form" title="<?php echo $this->translate('Edit Privilege'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
	com.em.Privilege.prototype.dialogButtons = {
			'<?php echo $this->translate('Update'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'privilege', 'action'=>'update-save')); ?>',
				type: "POST",
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						return false;
					}

					com.em.Privilege.prototype.processingDisplay(true);
					return true;
				},
				
				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.Privilege.prototype.showAlert(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.message == 'name_warning') {
									
							} else {
								$("#name").parent().find('.error').remove();	

								$("#name").parent().append('<ul id="error-name" class="error"><li>'+data.message+'</li> </ul>');						
								com.em.Privilege.prototype.showAlert(data.message, {header: com.em.Alert.FAILURE});
							}
						}
					}
				},
				
				complete: function(jqXHR, textStatus) {
					com.em.Privilege.prototype.processingDisplay(false);
				},
				
				error: function(jqXHR, textStatus, errorThrown) {
					dialogForm.dialog('close');
					com.em.Privilege.prototype.showAlert(errorThrown, {header: com.em.Alert.ERROR});
				}
			});
		},
		
		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>